#!/bin/bash
# ──────────────────────────────────────────────
#  PA Entrypoint — initializes SQLite DB if absent,
#  then hands off to the original Hermes command.
# ──────────────────────────────────────────────

DB_PATH="${HERMES_HOME:-/opt/data}/pa_index.db"
INIT_SQL="/opt/hermes/init/init_sqlite.sql"

if [ ! -f "$DB_PATH" ]; then
    echo "📦 pa_index.db not found — initializing SQLite database..."
    if [ -f "$INIT_SQL" ]; then
        sqlite3 "$DB_PATH" < "$INIT_SQL"
        echo "✅ Database created at $DB_PATH"
    else
        echo "⚠️  Warning: $INIT_SQL not found — skipping DB init."
    fi
else
    echo "✅ pa_index.db already exists — skipping init."
fi

# Ensure Langfuse observability plugin is enabled (persists to mounted volume)
echo "🔌 Enabling Langfuse observability plugin..."
/opt/hermes/.venv/bin/hermes plugins enable observability/langfuse

# ── Inject Langfuse credentials into ~/.hermes/.env ──
# Reason: Hermes credential_pool prefers ~/.hermes/.env over os.environ.
#         Without this file, Docker env vars are invisible to the plugin.
HERMES_ENV="${HOME}/.hermes/.env"
mkdir -p "$(dirname "$HERMES_ENV")"
{
  echo "# Auto-generated by entrypoint.sh — do not edit manually"
  echo "HERMES_LANGFUSE_PUBLIC_KEY=${HERMES_LANGFUSE_PUBLIC_KEY}"
  echo "HERMES_LANGFUSE_SECRET_KEY=${HERMES_LANGFUSE_SECRET_KEY}"
  echo "HERMES_LANGFUSE_BASE_URL=${HERMES_LANGFUSE_BASE_URL}"
  [ -n "$HERMES_LANGFUSE_DEBUG" ] && echo "HERMES_LANGFUSE_DEBUG=${HERMES_LANGFUSE_DEBUG}"
} > "$HERMES_ENV"
echo "✅ Langfuse credentials written to $HERMES_ENV"

# ── Auto-Setup for PA Stack ──
SETUP_SCRIPT="/opt/hermes/scripts/setup_dev.sh"
if [ -f "$SETUP_SCRIPT" ]; then
    echo "⚙️  Running development setup script..."
    bash "$SETUP_SCRIPT" || echo "⚠️  Warning: setup_dev.sh failed!"
fi

# Hand off to the original command (e.g. hermes gateway run)
exec "$@"
